In [ ]:
import requests

In [ ]:
url="https://books.toscrape.com/"

In [ ]:
response=requests.get(url)

In [ ]:
print(response.status_code)

200

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup=BeautifulSoup(response.text,"html.parser")

In [ ]:
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [ ]:
books=soup.find_all("article",class_="product_pod")

In [ ]:
len(books)

20

In [ ]:
books[0]

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [ ]:
books[0].h3.a["title"]

'A Light in the Attic'

In [ ]:
books[0].find("p",class_="price_color").text

'Â£51.77'

In [ ]:
books[0].find("p",class_="star-rating")["class"]

['star-rating', 'Three']

In [ ]:
for book in books:
    print(book.h3.a["title"])
    print(book.find("p",class_="price_color").text)
    print(book.find("p",class_="star-rating")["class"])

A Light in the Attic
Â£51.77
['star-rating', 'Three']
Tipping the Velvet
Â£53.74
['star-rating', 'One']
Soumission
Â£50.10
['star-rating', 'One']
Sharp Objects
Â£47.82
['star-rating', 'Four']
Sapiens: A Brief History of Humankind
Â£54.23
['star-rating', 'Five']
The Requiem Red
Â£22.65
['star-rating', 'One']
The Dirty Little Secrets of Getting Your Dream Job
Â£33.34
['star-rating', 'Four']
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Â£17.93
['star-rating', 'Three']
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Â£22.60
['star-rating', 'Four']
The Black Maria
Â£52.15
['star-rating', 'One']
Starving Hearts (Triangular Trade Trilogy, #1)
Â£13.99
['star-rating', 'Two']
Shakespeare's Sonnets
Â£20.66
['star-rating', 'Four']
Set Me Free
Â£17.46
['star-rating', 'Five']
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Â£52.29
['star-rating', 'Five']
Rip it Up and Start Again
Â£35.02
['star-rating', 'Five']
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Â£57.25
['star-rating', 'Three']
Olio
Â£23.88
['star-rating', 'One']
Mesaerion: The Best Science Fiction Stories 1800-1849
Â£37.59
['star-rating', 'One']
Libertarianism for Beginners
Â£51.33
['star-rating', 'Two']
It's Only the Himalayas
Â£45.17
['star-rating', 'Two']

In [ ]:
book_data=[]

In [ ]:
book_data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.find("p", class_="star-rating")["class"][1]

    book_data.append({
        "Title": title,
        "Price": price,
        "Rating": rating
    })

In [ ]:
book_data

[{'Title': 'A Light in the Attic', 'Price': 'Â£51.77', 'Rating': 'Three'},
 {'Title': 'Tipping the Velvet', 'Price': 'Â£53.74', 'Rating': 'One'},
 {'Title': 'Soumission', 'Price': 'Â£50.10', 'Rating': 'One'},
 {'Title': 'Sharp Objects', 'Price': 'Â£47.82', 'Rating': 'Four'},
 {'Title': 'Sapiens: A Brief History of Humankind',
  'Price': 'Â£54.23',
  'Rating': 'Five'},
 {'Title': 'The Requiem Red', 'Price': 'Â£22.65', 'Rating': 'One'},
 {'Title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'Price': 'Â£33.34',
  'Rating': 'Four'},
 {'Title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'Price': 'Â£17.93',
  'Rating': 'Three'},
 {'Title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Price': 'Â£22.60',
  'Rating': 'Four'},
 {'Title': 'The Black Maria', 'Price': 'Â£52.15', 'Rating': 'One'},
 {'Title': 'Starving Hearts (Triangular Trade Trilogy, #1)',
  'Price': 'Â£13.99',
  'Rating': 'Two'},
 {'Title': "Shakespeare's Sonnets", 'Price': 'Â£20.66', 'Rating': 'Four'},
 {'Title': 'Set Me Free', 'Price': 'Â£17.46', 'Rating': 'Five'},
 {'Title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'Price': 'Â£52.29',
  'Rating': 'Five'},
 {'Title': 'Rip it Up and Start Again', 'Price': 'Â£35.02', 'Rating': 'Five'},
 {'Title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Price': 'Â£57.25',
  'Rating': 'Three'},
 {'Title': 'Olio', 'Price': 'Â£23.88', 'Rating': 'One'},
 {'Title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Price': 'Â£37.59',
  'Rating': 'One'},
 {'Title': 'Libertarianism for Beginners',
  'Price': 'Â£51.33',
  'Rating': 'Two'},
 {'Title': "It's Only the Himalayas", 'Price': 'Â£45.17', 'Rating': 'Two'}]

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame(book_data)

In [ ]:
df

                                                Title    Price Rating
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two

In [ ]:
df.head()

                                   Title    Price Rating
0                   A Light in the Attic  Â£51.77  Three
1                     Tipping the Velvet  Â£53.74    One
2                             Soumission  Â£50.10    One
3                          Sharp Objects  Â£47.82   Four
4  Sapiens: A Brief History of Humankind  Â£54.23   Five

In [ ]:
df["Price"] = df["Price"].str.replace(r"[^0-9.]", "", regex=True)

In [ ]:
df["Price"] = df["Price"].astype(float)

In [ ]:
df.head()

                                   Title  Price Rating
0                   A Light in the Attic  51.77  Three
1                     Tipping the Velvet  53.74    One
2                             Soumission  50.10    One
3                          Sharp Objects  47.82   Four
4  Sapiens: A Brief History of Humankind  54.23   Five

In [ ]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating"] = df["Rating"].map(rating_map)

In [ ]:
df.head()

                                   Title  Price  Rating
0                   A Light in the Attic  51.77       3
1                     Tipping the Velvet  53.74       1
2                             Soumission  50.10       1
3                          Sharp Objects  47.82       4
4  Sapiens: A Brief History of Humankind  54.23       5

In [ ]:
df.dtypes

Title      object
Price     float64
Rating      int64
dtype: object

In [ ]:
df.to_csv("books.csv", index=False)

In [ ]:
import os

In [ ]:
os.listdir()

['.config', 'books.csv', 'sample_data']

In [ ]:
df.shape

(20, 3)

In [ ]:
from urllib.parse import urljoin

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

all_books = []

for page in range(1, 6):

    if page == 1:
        page_url = url
    else:
        page_url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(page_url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        title = book.h3.a["title"]

        price_text = book.find(
            "p", class_="price_color"
        ).text.strip()

        price_gbp = float(
            price_text.replace("£", "").replace("Â", "")
        )

        rating_text = book.find("p")["class"][1]
        rating = rating_map[rating_text]

        stock_text = book.find(
            "p", class_="instock availability"
        ).text.strip()

        in_stock = "In stock" in stock_text

        all_books.append({
            "Title": title,
            "price_gbp": price_gbp,
            "rating": rating,
            "in_stock": in_stock
        })

print("Total books:", len(all_books))

Total books: 100

In [ ]:
import pandas as pd

df = pd.DataFrame(all_books)

df["price_inr"] = df["price_gbp"] * 105.50

df.head()

,Title,price_gbp,rating,in_stock,price_inr
0,A Light in the Attic,51.77,3,True,5461.735
1,Tipping the Velvet,53.74,1,True,5669.570
2,Soumission,50.10,1,True,5285.550
3,Sharp Objects,47.82,4,True,5045.010
4,Sapiens: A Brief History of Humankind,54.23,5,True,5721.265

In [ ]:
df.dtypes

Title         object
price_gbp    float64
rating         int64
in_stock        bool
price_inr    float64
dtype: object

In [ ]:
import sqlite3

conn = sqlite3.connect("books.db")

df.to_sql("books", conn, if_exists="replace", index=False)

print("Books data stored successfully in database!")

Books data stored successfully in database!

In [ ]:
import pandas as pd

query = "SELECT * FROM books LIMIT 10"

result = pd.read_sql_query(query, conn)

result

,Title,price_gbp,rating,in_stock,price_inr
0,A Light in the Attic,51.77,3,1,5461.735
1,Tipping the Velvet,53.74,1,1,5669.570
2,Soumission,50.10,1,1,5285.550
3,Sharp Objects,47.82,4,1,5045.010
4,Sapiens: A Brief History of Humankind,54.23,5,1,5721.265
5,The Requiem Red,22.65,1,1,2389.575
6,The Dirty Little Secrets of Getting Your Dream...,33.34,4,1,3517.370
7,The Coming Woman: A Novel Based on the Life of...,17.93,3,1,1891.615
8,The Boys in the Boat: Nine Americans and Their...,22.60,4,1,2384.300
9,The Black Maria,52.15,1,1,5501.825

In [ ]:
query = """
SELECT Title, price_inr
FROM books
ORDER BY price_inr DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, conn)

result

                                               Title  price_inr
0       The Death of Humanity: and the Case for Life   6130.605
1                     Slow States of Collapse: Poems   6046.205
2  Our Band Could Be Your Life: Scenes from the A...   6039.875
3                                The Past Never Ends   5960.750
4  The Pioneer Woman Cooks: Dinnertime: Comfort C...   5951.255

In [ ]:
all_books[0]

{'Title': 'A Light in the Attic',
 'price_gbp': 51.77,
 'rating': 3,
 'in_stock': True}

In [ ]:
import requests
from bs4 import BeautifulSoup

all_books = []

for page in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        title = book.h3.a["title"]

        price_gbp = float(price_text.replace("Â£", "").replace("£", "").strip())

        rating_text = book.find("p", class_="star-rating")["class"][1]
        rating_map = {
            "One": 1,
            "Two": 2,
            "Three": 3,
            "Four": 4,
            "Five": 5
        }
        rating = rating_map.get(rating_text)

        availability = book.find(
            "p", class_="instock availability"
        ).get_text(" ", strip=True)

        in_stock = "In stock" in availability

        # Get the book's detail-page link
        book_link = book.h3.a["href"]
        detail_url = "https://books.toscrape.com/catalogue/" + book_link.replace("../", "")

        detail_response = requests.get(detail_url)
        detail_response.raise_for_status()

        detail_soup = BeautifulSoup(detail_response.text, "html.parser")

        breadcrumb = detail_soup.find("ul", class_="breadcrumb")
        breadcrumb_items = breadcrumb.find_all("li")

        category = breadcrumb_items[-2].get_text(strip=True)

        all_books.append({
            "Title": title,
            "price_gbp": price_gbp,
            "rating": rating,
            "availability": availability,
            "in_stock": in_stock,
            "category": category
        })

print("Total books:", len(all_books))
print("Total categories:", len(set(book["category"] for book in all_books)))

Total books: 100
Total categories: 29

In [ ]:
import pandas as pd

df = pd.DataFrame(all_books)

df = df.rename(columns={
    "Title": "title"
})

df["price_inr"] = df["price_gbp"] * 105.50

df["rating"] = df["rating"].astype("int64")
df["in_stock"] = df["in_stock"].astype(bool)
df["price_gbp"] = df["price_gbp"].astype(float)
df["price_inr"] = df["price_inr"].astype(float)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())

df.head()

Rows: 100
Columns: ['title', 'price_gbp', 'rating', 'availability', 'in_stock', 'category', 'price_inr']

,title,price_gbp,rating,availability,in_stock,category,price_inr
0,A Light in the Attic,51.77,3,In stock,True,Poetry,5461.735
1,Tipping the Velvet,51.77,1,In stock,True,Historical Fiction,5461.735
2,Soumission,51.77,1,In stock,True,Fiction,5461.735
3,Sharp Objects,51.77,4,In stock,True,Mystery,5461.735
4,Sapiens: A Brief History of Humankind,51.77,5,In stock,True,History,5461.735

In [ ]:
import pandas as pd

# 1. Convert the 'all_books' list from your previous cell into a DataFrame
df = pd.DataFrame(all_books)

# 2. Standardize column name if needed
if 'Title' in df.columns:
    df.rename(columns={'Title': 'title'}, inplace=True)

# 3. Add the price_inr column using Masai's fixed baseline rate (1 GBP = 105.50 INR)
GBP_TO_INR = 105.50
df['price_inr'] = (df['price_gbp'] * GBP_TO_INR).round(2)

# 4. Convert string ratings to integers if they aren't already
rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
if df['rating'].dtype == object:
    df['rating'] = df['rating'].map(rating_map)

# Display the prepared DataFrame
df.head()

,title,price_gbp,rating,availability,in_stock,category,price_inr
0,A Light in the Attic,51.77,3,In stock,True,Poetry,5461.74
1,Tipping the Velvet,51.77,1,In stock,True,Historical Fiction,5461.74
2,Soumission,51.77,1,In stock,True,Fiction,5461.74
3,Sharp Objects,51.77,4,In stock,True,Mystery,5461.74
4,Sapiens: A Brief History of Humankind,51.77,5,In stock,True,History,5461.74

In [ ]:
import sqlite3

# Connect to SQLite database file
conn = sqlite3.connect("data_pipeline.db")
cursor = conn.cursor()

# Enable Foreign Key constraints in SQLite
cursor.execute("PRAGMA foreign_keys = ON;")

# Reset tables if re-running
cursor.execute("DROP TABLE IF EXISTS books;")
cursor.execute("DROP TABLE IF EXISTS categories;")

# 1. Create normalized 2-table schema
cursor.execute("""
    CREATE TABLE categories (
        category_id INTEGER PRIMARY KEY AUTOINCREMENT,
        category_name TEXT UNIQUE NOT NULL
    );
""")

cursor.execute("""
    CREATE TABLE books (
        book_id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT NOT NULL,
        price_gbp REAL NOT NULL,
        price_inr REAL NOT NULL,
        rating INTEGER NOT NULL,
        in_stock INTEGER NOT NULL,
        category_id INTEGER NOT NULL,
        FOREIGN KEY (category_id) REFERENCES categories (category_id)
    );
""")

# 2. Insert unique categories into 'categories' table
unique_categories = df[['category']].drop_duplicates().rename(columns={'category': 'category_name'})
unique_categories.to_sql('categories', conn, if_exists='append', index=False)

# 3. Retrieve category IDs and map them to the books DataFrame
cat_lookup = pd.read_sql("SELECT category_id, category_name FROM categories;", conn)
df_merged = df.merge(cat_lookup, left_on='category', right_on='category_name')

# Ensure in_stock is 1 or 0 integer
df_merged['in_stock'] = df_merged['in_stock'].astype(int)

# 4. Insert books into 'books' table
books_to_insert = df_merged[['title', 'price_gbp', 'price_inr', 'rating', 'in_stock', 'category_id']]
books_to_insert.to_sql('books', conn, if_exists='append', index=False)

conn.close()
print("✓ SQLite Database successfully created and loaded with PK/FK constraints!")

✓ SQLite Database successfully created and loaded with PK/FK constraints!

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("data_pipeline.db")

queries = {
    "1. SELECT / WHERE / ORDER BY / LIMIT (5 Cheapest In-Stock Books)": """
        SELECT title, price_gbp, price_inr
        FROM books
        WHERE in_stock = 1
        ORDER BY price_gbp ASC
        LIMIT 5;
    """,

    "2. DISTINCT (Distinct Ratings Available)": """
        SELECT DISTINCT rating
        FROM books
        ORDER BY rating DESC;
    """,

    "3. IN (Books with 4 or 5 Star Ratings)": """
        SELECT title, rating, price_inr
        FROM books
        WHERE rating IN (4, 5)
        LIMIT 5;
    """,

    "4. BETWEEN (Books Priced Between 20.00 and 40.00 GBP)": """
        SELECT title, price_gbp, price_inr
        FROM books
        WHERE price_gbp BETWEEN 20.00 AND 40.00
        ORDER BY price_gbp DESC
        LIMIT 5;
    """,

    "5. JOIN (Top 10 Highest-Rated Books with Category Names)": """
        SELECT b.title, c.category_name, b.rating, b.price_gbp, b.price_inr
        FROM books b
        JOIN categories c ON b.category_id = c.category_id
        WHERE b.rating = 5
        ORDER BY b.price_gbp DESC
        LIMIT 10;
    """
}

for label, sql in queries.items():
    print(f"\n================ {label} ================")
    display(pd.read_sql(sql, conn))

conn.close()

================ 1. SELECT / WHERE / ORDER BY / LIMIT (5 Cheapest In-Stock Books) ================

                                   title  price_gbp  price_inr
0                   A Light in the Attic      51.77    5461.74
1                     Tipping the Velvet      51.77    5461.74
2                             Soumission      51.77    5461.74
3                          Sharp Objects      51.77    5461.74
4  Sapiens: A Brief History of Humankind      51.77    5461.74

================ 2. DISTINCT (Distinct Ratings Available) ================

   rating
0       5
1       4
2       3
3       2
4       1

================ 3. IN (Books with 4 or 5 Star Ratings) ================

                                               title  rating  price_inr
0                                      Sharp Objects       4    5461.74
1              Sapiens: A Brief History of Humankind       5    5461.74
2  The Dirty Little Secrets of Getting Your Dream...       4    5461.74
3  The Boys in the Boat: Nine Americans and Their...       4    5461.74
4                              Shakespeare's Sonnets       4    5461.74

================ 4. BETWEEN (Books Priced Between 20.00 and 40.00 GBP) ================

Empty DataFrame
Columns: [title, price_gbp, price_inr]
Index: []

================ 5. JOIN (Top 10 Highest-Rated Books with Category Names) ================

,title,category_name,rating,price_gbp,price_inr
0,Sapiens: A Brief History of Humankind,History,5,51.77,5461.74
1,Set Me Free,Young Adult,5,51.77,5461.74
2,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,5,51.77,5461.74
3,Rip it Up and Start Again,Music,5,51.77,5461.74
4,Chase Me (Paris Nights #2),Romance,5,51.77,5461.74
5,Black Dust,Romance,5,51.77,5461.74
6,Worlds Elsewhere: Journeys Around Shakespeareâ...,Nonfiction,5,51.77,5461.74
7,The Four Agreements: A Practical Guide to Pers...,Spirituality,5,51.77,5461.74
8,The Elephant Tree,Thriller,5,51.77,5461.74
9,Sophie's World,Philosophy,5,51.77,5461.74

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("data_pipeline.db")

# Method A: Direct SQL JOIN
sql_join = """
    SELECT b.title, c.category_name, b.rating, b.price_gbp, b.price_inr
    FROM books b
    JOIN categories c ON b.category_id = c.category_id
    WHERE b.rating = 5
    ORDER BY b.price_gbp DESC
    LIMIT 10;
"""
sql_df = pd.read_sql(sql_join, conn)

# Method B: Pure Pandas read + pd.merge()
df_books = pd.read_sql("SELECT * FROM books;", conn)
df_categories = pd.read_sql("SELECT * FROM categories;", conn)
conn.close()

pandas_df = (
    pd.merge(df_books, df_categories, on="category_id")
    .query("rating == 5")
    .sort_values(by="price_gbp", ascending=False)
    [['title', 'category_name', 'rating', 'price_gbp', 'price_inr']]
    .head(10)
    .reset_index(drop=True)
)

sql_df = sql_df.reset_index(drop=True)

# Display both side by side
print("--- SQL JOIN Output ---")
display(sql_df)

print("\n--- Pandas pd.merge Output ---")
display(pandas_df)

# Equivalence Check Assert
assert sql_df.equals(pandas_df), "Mismatch between SQL and Pandas outputs!"
print("\n SUCCESS: Both SQL JOIN and Pandas pd.merge produced identical outputs!")

--- SQL JOIN Output ---

,title,category_name,rating,price_gbp,price_inr
0,Sapiens: A Brief History of Humankind,History,5,51.77,5461.74
1,Set Me Free,Young Adult,5,51.77,5461.74
2,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,5,51.77,5461.74
3,Rip it Up and Start Again,Music,5,51.77,5461.74
4,Chase Me (Paris Nights #2),Romance,5,51.77,5461.74
5,Black Dust,Romance,5,51.77,5461.74
6,Worlds Elsewhere: Journeys Around Shakespeareâ...,Nonfiction,5,51.77,5461.74
7,The Four Agreements: A Practical Guide to Pers...,Spirituality,5,51.77,5461.74
8,The Elephant Tree,Thriller,5,51.77,5461.74
9,Sophie's World,Philosophy,5,51.77,5461.74

--- Pandas pd.merge Output ---

,title,category_name,rating,price_gbp,price_inr
0,Sapiens: A Brief History of Humankind,History,5,51.77,5461.74
1,Set Me Free,Young Adult,5,51.77,5461.74
2,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,5,51.77,5461.74
3,Rip it Up and Start Again,Music,5,51.77,5461.74
4,Chase Me (Paris Nights #2),Romance,5,51.77,5461.74
5,Black Dust,Romance,5,51.77,5461.74
6,Worlds Elsewhere: Journeys Around Shakespeareâ...,Nonfiction,5,51.77,5461.74
7,The Four Agreements: A Practical Guide to Pers...,Spirituality,5,51.77,5461.74
8,The Elephant Tree,Thriller,5,51.77,5461.74
9,Sophie's World,Philosophy,5,51.77,5461.74

 SUCCESS: Both SQL JOIN and Pandas pd.merge produced identical outputs!